---
- name: Deploy Node.js app from GitHub on Ubuntu EC2
  hosts: all
  become: true

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install Node.js, npm, and Git
      apt:
        name:
          - nodejs
          - npm
          - git
        state: present

    - name: Clone or update Node.js app repository
      git:
        repo: "https://github.com/UdayParkar/AWS-EC2-instance.git"
        dest: "/home/ubuntu/AWS-EC2-instance"
        version: main
        force: yes

    - name: Install npm dependencies
      command: npm install
      args:
        chdir: /home/ubuntu/AWS-EC2-instance
      ignore_errors: yes

    - name: Ensure express is installed
      command: npm install express
      args:
        chdir: /home/ubuntu/AWS-EC2-instance

    # - name: Stop any running Node.js apps
    #   shell: pkill -f node || true
    #   ignore_errors: yes

    - name: Start Node.js app in background with logs
      shell: nohup node index.js > /home/ubuntu/server.log 2>&1 &
      args:
        chdir: /home/ubuntu/AWS-EC2-instance
